-- Categorias terapeuticas (amplas) por principio ativo — 2026-10-02.
-- Aplicado pelo setup.py; idempotente (ON CONFLICT DO NOTHING).
INSERT INTO prescricao.categoria_medicamento (principio_ativo, categoria) VALUES
('AAS', 'Analgésico'),
('ACEBROFILINA', 'Respiratório'),
('ACETILCISTEÍNA', 'Respiratório'),
('ACICLOVIR', 'Antifúngico/antiviral'),
('AGOMELATINA', 'Antidepressivo'),
('ALBENDAZOL', 'Antiparasitário'),
('ALENDRONATO DE SÓDIO', 'Outros'),
('ALOPURINOL', 'Antigotoso'),
('ALPRAZOLAM', 'Ansiolítico/hipnótico'),
('AMANTADINA', 'Antiparkinsoniano'),
('AMBROXOL', 'Respiratório'),
('AMITRIPTILINA', 'Antidepressivo'),
('AMOXICILINA', 'Antibiótico'),
('AMOXICILINA + CLAVULANATO', 'Antibiótico'),
('ANASTROZOL', 'Hormônio/reposição'),
('ANLODIPINO', 'Cardiovascular'),
('APIXABANA', 'Cardiovascular'),
('ARIPIPRAZOL', 'Antipsicótico'),
('ATENOLOL', 'Cardiovascular'),
('ATOMOXETINA', 'Psicoestimulante/TDAH'),
('ATORVASTATINA', 'Cardiovascular'),
('AZITROMICINA', 'Antibiótico'),
('BACILLUS CLAUSII', 'Gastrointestinal'),
('BACLOFENO', 'Relaxante muscular'),
('BECLOMETASONA', 'Respiratório'),
('BETAMETASONA', 'Anti-inflamatório/corticoide'),
('BETAMETASONA + CLOTRIMAZOL', 'Dermatológico'),
('BETAMETASONA + CLOTRIMAZOL + GENTAMICINA', 'Dermatológico'),
('BILASTINA', 'Antialérgico'),
('BIPERIDENO', 'Antiparkinsoniano'),
('BISOPROLOL', 'Cardiovascular'),
('BREXPIPRAZOL', 'Antipsicótico'),
('BROMOPRIDA', 'Antiemético/antivertiginoso'),
('BUDESONIDA', 'Respiratório'),
('BUDESONIDA + FORMOTEROL', 'Respiratório'),
('BUPROPIONA', 'Antidepressivo'),
('BUPROPIONA + NALTREXONA', 'Antidiabético/obesidade'),
('BUSPIRONA', 'Ansiolítico/hipnótico'),
('BUTILBROMETO DE ESCOPOLAMINA', 'Gastrointestinal'),
('CANABIDIOL', 'Canabinoide'),
('CAPTOPRIL', 'Cardiovascular'),
('CARBAMAZEPINA', 'Estabilizador de humor'),
('CARBONATO DE LÍTIO', 'Estabilizador de humor'),
('CARVEDILOL', 'Cardiovascular'),
('CEFADROXILA', 'Antibiótico'),
('CEFALEXINA', 'Antibiótico'),
('CEFTRIAXONA', 'Antibiótico'),
('CEFUROXIMA', 'Antibiótico'),
('CELECOXIBE', 'Anti-inflamatório/corticoide'),
('CETOCONAZOL', 'Antifúngico/antiviral'),
('CETOPROFENO', 'Anti-inflamatório/corticoide'),
('CETOROLACO', 'Anti-inflamatório/corticoide'),
('CICLOBENZAPRINA', 'Relaxante muscular'),
('CICLOBENZAPRINA + CAFEÍNA', 'Relaxante muscular'),
('CILOSTAZOL', 'Cardiovascular'),
('CIPROFIBRATO', 'Cardiovascular'),
('CIPROFLOXACINO', 'Antibiótico'),
('CIPROFLOXACINO + HIDROCORTISONA', 'Antibiótico'),
('CITALOPRAM', 'Antidepressivo'),
('CITICOLINA', 'Cognição/demência'),
('CLARITROMICINA', 'Antibiótico'),
('CLINDAMICINA', 'Antibiótico'),
('CLOBAZAM', 'Ansiolítico/hipnótico'),
('CLOBETASOL', 'Dermatológico'),
('CLOMIFENO', 'Hormônio/reposição'),
('CLOMIPRAMINA', 'Antidepressivo'),
('CLONAZEPAM', 'Ansiolítico/hipnótico'),
('CLONIDINA', 'Cardiovascular'),
('CLOPIDOGREL', 'Cardiovascular'),
('CLORPROMAZINA', 'Antipsicótico'),
('CLOZAPINA', 'Antipsicótico'),
('CODEÍNA', 'Analgésico'),
('COENZIMA Q10', 'Vitamina/suplemento'),
('COLECALCIFEROL', 'Vitamina/suplemento'),
('COMPLEXO B', 'Vitamina/suplemento'),
('CREATINA', 'Vitamina/suplemento'),
('DAPAGLIFLOZINA', 'Antidiabético/obesidade'),
('DENOSUMABE', 'Outros'),
('DESLORATADINA', 'Antialérgico'),
('DESMOPRESSINA', 'Hormônio/reposição'),
('DESVENLAFAXINA', 'Antidepressivo'),
('DEXAMETASONA', 'Anti-inflamatório/corticoide'),
('DEXCLORFENIRAMINA', 'Antialérgico'),
('DEXLANSOPRAZOL', 'Gastrointestinal'),
('DHEA', 'Hormônio/reposição'),
('DIAZEPAM', 'Ansiolítico/hipnótico'),
('DICLOFENACO', 'Anti-inflamatório/corticoide'),
('DIDROGESTERONA', 'Hormônio/reposição'),
('DIMENIDRINATO + PIRIDOXINA', 'Antiemético/antivertiginoso'),
('DIPIRONA', 'Analgésico'),
('DIPIRONA + ADIFENINA', 'Analgésico'),
('DIVALPROATO DE SÓDIO', 'Estabilizador de humor'),
('DOMPERIDONA', 'Antiemético/antivertiginoso'),
('DONEPEZILA', 'Cognição/demência'),
('DOXAZOSINA', 'Cardiovascular'),
('DOXEPINA', 'Antidepressivo'),
('DOXICICLINA', 'Antibiótico'),
('DULOXETINA', 'Antidepressivo'),
('DUTASTERIDA', 'Urológico'),
('DUTASTERIDA + TANSULOSINA', 'Urológico'),
('ENALAPRIL', 'Cardiovascular'),
('ENOXAPARINA', 'Cardiovascular'),
('ESCITALOPRAM', 'Antidepressivo'),
('ESCOPOLAMINA', 'Gastrointestinal'),
('ESCOPOLAMINA + DIPIRONA', 'Analgésico'),
('ESOMEPRAZOL', 'Gastrointestinal'),
('ESPIRONOLACTONA', 'Cardiovascular'),
('ESTRADIOL', 'Hormônio/reposição'),
('ETIRACETAM', 'Anticonvulsivante/neuromodulador'),
('ETORICOXIBE', 'Anti-inflamatório/corticoide'),
('EZETIMIBA', 'Cardiovascular'),
('FENAZOPIRIDINA', 'Urológico'),
('FENITOÍNA', 'Anticonvulsivante/neuromodulador'),
('FENOBARBITAL', 'Anticonvulsivante/neuromodulador'),
('FERRO', 'Vitamina/suplemento'),
('FEXOFENADINA', 'Antialérgico'),
('FINASTERIDA', 'Urológico'),
('FLUCONAZOL', 'Antifúngico/antiviral'),
('FLUOXETINA', 'Antidepressivo'),
('FLUTICASONA', 'Respiratório'),
('FLUVOXAMINA', 'Antidepressivo'),
('FOSFOMICINA', 'Antibiótico'),
('FUROSEMIDA', 'Cardiovascular'),
('GABAPENTINA', 'Anticonvulsivante/neuromodulador'),
('GALANTAMINA', 'Cognição/demência'),
('GESTRINONA', 'Hormônio/reposição'),
('GLIBENCLAMIDA', 'Antidiabético/obesidade'),
('GLICAZIDA', 'Antidiabético/obesidade'),
('GLICLAZIDA', 'Antidiabético/obesidade'),
('HALOPERIDOL', 'Antipsicótico'),
('HESPERIDINA + DIOSMINA', 'Cardiovascular'),
('HIDROCLOROTIAZIDA', 'Cardiovascular'),
('HIDROCORTISONA', 'Anti-inflamatório/corticoide'),
('HIDROXIZINA', 'Ansiolítico/hipnótico'),
('IBUPROFENO', 'Anti-inflamatório/corticoide'),
('IMIPRAMINA', 'Antidepressivo'),
('INDAPAMIDA', 'Cardiovascular'),
('INSULINA DEGLUDECA + LIRAGLUTIDA', 'Antidiabético/obesidade'),
('INSULINA GLARGINA', 'Antidiabético/obesidade'),
('INSULINA NPH', 'Antidiabético/obesidade'),
('INSULINA REGULAR', 'Antidiabético/obesidade'),
('IPRATRÓPIO', 'Respiratório'),
('ISOTRETINOÍNA', 'Dermatológico'),
('ITRACONAZOL', 'Antifúngico/antiviral'),
('IVERMECTINA', 'Antiparasitário'),
('LACOSAMIDA', 'Anticonvulsivante/neuromodulador'),
('LACTULOSE', 'Gastrointestinal'),
('LAMOTRIGINA', 'Estabilizador de humor'),
('LEVETIRACETAM', 'Anticonvulsivante/neuromodulador'),
('LEVODOPA + BENSERAZIDA', 'Antiparkinsoniano'),
('LEVOFLOXACINO', 'Antibiótico'),
('LEVOMEPROMAZINA', 'Antipsicótico'),
('LEVOTIROXINA', 'Hormônio/reposição'),
('LIMECICLINA', 'Antibiótico'),
('LISDEXANFETAMINA', 'Psicoestimulante/TDAH'),
('LOPERAMIDA', 'Gastrointestinal'),
('LORATADINA', 'Antialérgico'),
('LOSARTANA', 'Cardiovascular'),
('LURASIDONA', 'Antipsicótico'),
('LÍTIO', 'Estabilizador de humor'),
('MECOBALAMINA', 'Vitamina/suplemento'),
('MELATONINA', 'Ansiolítico/hipnótico'),
('MELOXICAM', 'Anti-inflamatório/corticoide'),
('MEMANTINA', 'Cognição/demência'),
('METFORMINA', 'Antidiabético/obesidade'),
('METILFENIDATO', 'Psicoestimulante/TDAH'),
('METOCLOPRAMIDA', 'Antiemético/antivertiginoso'),
('METOPROLOL', 'Cardiovascular'),
('METOTREXATO', 'Outros'),
('METRONIDAZOL', 'Antibiótico'),
('MICONAZOL', 'Antifúngico/antiviral'),
('MINOXIDIL', 'Dermatológico'),
('MIRTAZAPINA', 'Antidepressivo'),
('MOMETASONA', 'Respiratório'),
('MOXIFLOXACINO', 'Antibiótico'),
('MOXIFLOXACINO + DEXAMETASONA', 'Antibiótico'),
('MUPIROCINA', 'Antibiótico'),
('NADH', 'Vitamina/suplemento'),
('NALTREXONA', 'Outros'),
('NANDROLONA', 'Hormônio/reposição'),
('NAPROXENO', 'Anti-inflamatório/corticoide'),
('NEOMICINA + BACITRACINA', 'Antibiótico'),
('NIMESULIDA', 'Anti-inflamatório/corticoide'),
('NITAZOXANIDA', 'Antiparasitário'),
('NITROFURANTOÍNA', 'Antibiótico'),
('NORFLOXACINO', 'Antibiótico'),
('NORTRIPTILINA', 'Antidepressivo'),
('OLANZAPINA', 'Antipsicótico'),
('OLMESARTANA', 'Cardiovascular'),
('OMEPRAZOL', 'Gastrointestinal'),
('ONDANSETRONA', 'Antiemético/antivertiginoso'),
('ORLISTATE', 'Antidiabético/obesidade'),
('OSELTAMIVIR', 'Antifúngico/antiviral'),
('OXANDROLONA', 'Hormônio/reposição'),
('OXCARBAZEPINA', 'Estabilizador de humor'),
('OXIMETOLONA', 'Hormônio/reposição'),
('PANTOPRAZOL', 'Gastrointestinal'),
('PARACETAMOL', 'Analgésico'),
('PARACETAMOL + CODEÍNA', 'Analgésico'),
('PARACETAMOL + PSEUDOEFEDRINA', 'Analgésico'),
('PARACETAMOL + TRAMADOL', 'Analgésico'),
('PAROXETINA', 'Antidepressivo'),
('PENICILINA BENZATINA', 'Antibiótico'),
('PERICIAZINA', 'Antipsicótico'),
('PIRACETAM', 'Cognição/demência'),
('POLIETILENOGLICOL', 'Gastrointestinal'),
('POLIMIXINA B + NEOMICINA + HIDROCORTISONA', 'Antibiótico'),
('PRAMIPEXOL', 'Antiparkinsoniano'),
('PRASTERONA', 'Hormônio/reposição'),
('PRAZOSINA', 'Cardiovascular'),
('PREDNISOLONA', 'Anti-inflamatório/corticoide'),
('PREDNISONA', 'Anti-inflamatório/corticoide'),
('PREGABALINA', 'Anticonvulsivante/neuromodulador'),
('PRIMIDONA', 'Anticonvulsivante/neuromodulador'),
('PROBIÓTICO', 'Gastrointestinal'),
('PROGESTERONA', 'Hormônio/reposição'),
('PROMETAZINA', 'Antialérgico'),
('PROPRANOLOL', 'Cardiovascular'),
('QUETIAPINA', 'Antipsicótico'),
('RACECADOTRILA', 'Gastrointestinal'),
('RIFAMICINA', 'Antibiótico'),
('RISPERIDONA', 'Antipsicótico'),
('RIVAROXABANA', 'Cardiovascular'),
('RIVASTIGMINA', 'Cognição/demência'),
('ROSUVASTATINA', 'Cardiovascular'),
('SACCHAROMYCES BOULARDII', 'Gastrointestinal'),
('SAIS DE REIDRATAÇÃO ORAL', 'Outros'),
('SALBUTAMOL', 'Respiratório'),
('SECNIDAZOL', 'Antibiótico'),
('SEMAGLUTIDA', 'Antidiabético/obesidade'),
('SERTRALINA', 'Antidepressivo'),
('SILDENAFILA', 'Urológico'),
('SIMETICONA', 'Gastrointestinal'),
('SINVASTATINA', 'Cardiovascular'),
('SOMATROPINA', 'Hormônio/reposição'),
('SORO DE REIDRATAÇÃO ORAL', 'Outros'),
('SORO FISIOLÓGICO', 'Outros'),
('SULFADIAZINA DE PRATA', 'Antibiótico'),
('SULFAMETOXAZOL + TRIMETOPRIMA', 'Antibiótico'),
('SULTOPRIDA', 'Antipsicótico'),
('SUXAMETÔNIO', 'Outros'),
('TADALAFILA', 'Urológico'),
('TANSULOSINA', 'Urológico'),
('TERBINAFINA', 'Antifúngico/antiviral'),
('TESTOSTERONA', 'Hormônio/reposição'),
('TETRACICLINA', 'Antibiótico'),
('TIAMINA', 'Vitamina/suplemento'),
('TIRZEPATIDA', 'Antidiabético/obesidade'),
('TOBRAMICINA', 'Antibiótico'),
('TOBRAMICINA + DEXAMETASONA', 'Antibiótico'),
('TOPIRAMATO', 'Anticonvulsivante/neuromodulador'),
('TRAMADOL', 'Analgésico'),
('TRAZODONA', 'Antidepressivo'),
('VALACICLOVIR', 'Antifúngico/antiviral'),
('VALPROATO DE SÓDIO', 'Estabilizador de humor'),
('VALSARTANA', 'Cardiovascular'),
('VENLAFAXINA', 'Antidepressivo'),
('VITAMINA B12', 'Vitamina/suplemento'),
('VITAMINA C', 'Vitamina/suplemento'),
('VITAMINA D', 'Vitamina/suplemento'),
('VORTIOXETINA', 'Antidepressivo'),
('ZOLPIDEM', 'Ansiolítico/hipnótico'),
('ÁCIDO ACETILSALICÍLICO', 'Analgésico'),
('ÁCIDO FÓLICO', 'Vitamina/suplemento'),
('ÁCIDO TRANEXÂMICO', 'Cardiovascular'),
('ÁCIDO VALPRÓICO', 'Estabilizador de humor'),
('ÓLEO MINERAL', 'Gastrointestinal'),
('ÔMEGA 3', 'Vitamina/suplemento')
ON CONFLICT (principio_ativo) DO NOTHING;
